<a href="https://colab.research.google.com/github/2203A52227/DEEP-LEARNING_2227/blob/main/2203A52227_DL_ASS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
y_act=[20,30,40,50,60]
y_pred=[20.5,30.3,40.2,50.6,60.7]

length=len(y_act)

sum=0
mae=0
for i in range(length):
  sum+=(y_act[i] -y_pred[i])**2

for i in range(length):
  mae+=abs(y_act[i] -y_pred[i])

mse=(sum)/length
print(mse)

#calculate root
import math
rmse=math.sqrt(mse)
print(rmse)

mae=(mae)/length
print(mae)

0.24600000000000147
0.49598387070549127
0.4600000000000016


In [ ]:
#using libraries
import numpy as np
from sklearn.metrics import mean_squared_error,mean_absolute_error

y_act=[20,30,40,50,60]
y_pred=[20.5,30.3,40.2,50.6,60.7]

mse=mean_squared_error(y_act,y_pred)
print(mse)

rmse=np.sqrt(mse)
print(rmse)

mae=mean_absolute_error(y_act,y_pred)
print(mae)

0.24600000000000147
0.49598387070549127
0.4600000000000016


In [ ]:
#2
#calculate confusion matrix without predefined modules
y_act=[0,0,0,0,0,1,1,1,1,1,2,2,2,2,2]
y_pred=[0,0,1,2,2,1,0,2,0,2,0,0,1,2,2]

length=len(y_act)

confusion_matrix=[[0,0,0,],[0,0,0],[0,0,0]]

for i in range(length):
  if y_act[i]==0:
    if y_pred[i]==0:
      confusion_matrix[0][0]+=1
    elif y_pred[i]==1:
      confusion_matrix[0][1]+=1
    else:
      confusion_matrix[0][2]+=1
  elif y_act[i]==1:
    if y_pred[i]==0:
      confusion_matrix[1][0]+=1
    elif y_pred[i]==1:
      confusion_matrix[1][1]+=1
    else:
      confusion_matrix[1][2]+=1
  else:
    if y_pred[i]==0:
      confusion_matrix[2][0]+=1
    elif y_pred[i]==1:
      confusion_matrix[2][1]+=1
    else:
      confusion_matrix[2][2]+=1
print(confusion_matrix)

#Accuracy
accuracy=confusion_matrix[0][0]+confusion_matrix[1][1]+confusion_matrix[2][2]
accuracy=accuracy/length
print(accuracy)

[[2, 1, 2], [2, 1, 2], [2, 1, 2]]
0.3333333333333333


In [ ]:
y_act=[0,0,0,0,0,1,1,1,1,1,2,2,2,2,2]
y_pred=[0,0,1,2,2,1,0,2,0,2,0,0,1,2,2]

length=len(y_act)

from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix=confusion_matrix(y_act,y_pred)
print(confusion_matrix)

accuracy=accuracy_score(y_act,y_pred)
print(accuracy)

[[2 1 2]
 [2 1 2]
 [2 1 2]]
0.3333333333333333
